#!/usr/bin/env bash

set -euo pipefail

here="$(dirname "$0")"

rm -rf result
mkdir -p .cache

fetch_cache() {
  while read date; do
    cache=".cache/$(echo $date | tr '/' '_')"
    if ! [[ -f "$cache" ]]; then
      echo "Downloading $cache" >&2
      "$here"/scripts/fetch $date 2>/dev/null > "$cache"
    fi
    echo "$cache"
  done	
}

add_date() {
  while read line; do
    echo $line | sed "s/^/$1, /"
  done
}

parse_file() {
  while read file; do
    date="$(echo $file | sed 's/^.cache\///' | awk -F'_' '{printf "%s-%s-%s", $3, $1, $2}')"
    cat "$file" | "$here"/scripts/parse | add_date "$date" | sort -k1 -t, -n
  done	
}

"$here"/scripts/all-dates | fetch_cache | parse_file > result
cat result | awk -F, '{print $4}' | sort | uniq > horse
cat result | awk -F, '{print $5}' | sort | uniq > driver
