#!/usr/bin/env python3

import fileinput, json, random
import numpy as np
from itertools import chain

# From each race, draw n samples from the skill distributions of ecah horse and driver
# and generate a traning sample. 15 was chosen because it yields about 900k samples, so
# pretty arbitrary.
n = 25

def race_generator(race):
    for i in range(n):
        yield [
            np.random.normal(race['horseMu'], race['horseSigma']).tolist(),
            np.random.normal(race['driverMu'], race['driverSigma']).tolist(),
            np.array(np.array(race['finishOrder']) == 1, dtype='int').tolist()
        ]

def read_data():
    return json.loads(u"".join([x for x in fileinput.input()]))

def generate_samples(data):
    return list(chain.from_iterable((x for x in map(race_generator, data))))

data = read_data()
result = generate_samples(data)
random.shuffle(result)
print(json.dumps(result))
