#!/usr/bin/env bash

# Filters on Swedish races where status == results. Then collects the interesting
# values for each race file and outputs a long json dictionary with all the races/values.

find .cache/races -type f | sort \
    | xargs jq 'select(.track.countryCode == "SE" and .status == "results")' \
    | jq '{
            startTime: .startTime,
            horseId: [.starts[].horse.id],
            horseName: [.starts[].horse.name],
            driverId: [.starts[].driver.id],
            driverName: [(.starts[] | .driver.firstName + " " + .driver.lastName)],
            place: [.starts[].result.place],
            finishOrder: [.starts[].result.finishOrder],
            finalOdds: [.starts[].result.finalOdds]
          }' \
    | jq -s . | jq 'sort_by(.startTime)'
