#!/usr/bin/env python3

import atg, fileinput, json

races = set()

for day in fileinput.input():
  data = json.loads(day)
  for game_key, game_list in data['games'].items():
    for game in game_list:
      for race in game['races']:
          races.add(race)
          
for race in races: print(json.dumps(atg.get_race(race)))

