#!/usr/bin/env bash

set -euo pipefail

here="$(dirname "$0")"

filter_dates() {
  while read line; do
    date="$(echo $line | sed 's/^.cache\///' | awk -F'/' '{printf "%s-%s-%s", $3, $1, $2}')"
    find result/${date}* &>/dev/null || echo $line
  done
}

"$here"/all-dates | filter_dates
