#!/usr/bin/env bash

set -euo pipefail

here="$(dirname "$0")"

filter_dates() {
  while read date; do
      [[ -f ".cache/days/${date}.json" ]] \
	  || ! find ".cache/races" -name "${date}_*" &>/dev/null \
	  || echo "$date"
  done
}

"$here"/all-dates | filter_dates
