#!/usr/bin/env python3

import fileinput
from lxml import etree
from io import StringIO

html = u"".join([line for line in fileinput.input()])
parser = etree.XMLParser(recover=True)
tree = etree.parse(StringIO(html), parser)

races = [etree.ElementTree(x) for x in tree.xpath("//div[contains(@class, 'leg-tab-pane')]")]
for race in races:
    name = [x.strip() for x in race.xpath("div[contains(@class, 'race-heading')]//h4/text()")][0]
    placement = race.xpath("//div[contains(@class, 'placement')]//h4/text()")
    horse = [x.strip() for x in race.xpath("//div[contains(@class, 'equipage')]//h4/text()")]
    driver = [x.strip() for x in race.xpath("//div[contains(@class, 'equipage')]//h5/text()")]

    for row in zip(placement, horse, driver):
        print(", ".join([name] + list(row)))
