#!/usr/bin/env python3

import fileinput
import pandas as pd
from io import StringIO

data = StringIO("".join([line for line in fileinput.input()]))
df = pd.read_csv(data, 
  index_col=0, 
  parse_dates=True, 
  delimiter=',', 
  names=['Date', 'Race', 'Placement', 'Horse', 'Driver'])
df.to_pickle('result.pickle')

